import type { CollectionModel } from "pocketbase";

export const COLLECTION_IDS = {
  administradores: "evadmin00000001",
  cuentasServicio: "evservice000001",
  eventos: "evevents0000001",
  inscripciones: "evregist0000001",
  auditoria: "evaudit0000001",
  certificados: "evcerts0000001",
  envios: "evmails0000001",
} as const;

const protectedRule =
  '@request.auth.id != "" && (@request.auth.role = "admin" || @request.auth.role = "service")';

const protectedCollection = {
  listRule: protectedRule,
  viewRule: protectedRule,
  createRule: protectedRule,
  updateRule: protectedRule,
  deleteRule: protectedRule,
};

export const pocketBaseSchema = [
  {
    id: COLLECTION_IDS.administradores,
    name: "administradores",
    type: "auth",
    listRule: null,
    viewRule:
      'id = @request.auth.id || @request.auth.role = "service"',
    createRule: null,
    updateRule: "id = @request.auth.id",
    deleteRule: null,
    fields: [
      { name: "nombre", type: "text", required: true, max: 120 },
      { name: "role", type: "select", required: true, maxSelect: 1, values: ["admin"] },
    ],
    passwordAuth: { enabled: true, identityFields: ["email"] },
  },
  {
    id: COLLECTION_IDS.cuentasServicio,
    name: "cuentas_servicio",
    type: "auth",
    listRule: null,
    viewRule: "id = @request.auth.id",
    createRule: null,
    updateRule: null,
    deleteRule: null,
    fields: [
      { name: "nombre", type: "text", required: true, max: 120 },
      { name: "role", type: "select", required: true, maxSelect: 1, values: ["service"] },
    ],
    passwordAuth: { enabled: true, identityFields: ["email"] },
  },
  {
    ...protectedCollection,
    id: COLLECTION_IDS.eventos,
    name: "eventos",
    type: "base",
    fields: [
      { name: "titulo", type: "text", required: true, max: 160 },
      { name: "descripcion", type: "editor", required: true, maxSize: 20000 },
      {
        name: "slug",
        type: "text",
        required: true,
        max: 100,
        pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$",
      },
      { name: "inicio", type: "date", required: true },
      { name: "fin", type: "date", required: true },
      { name: "lugar", type: "text", required: true, max: 240 },
      { name: "cupo", type: "number", required: true, min: 1, max: 100000, onlyInt: true },
      { name: "inscripcion_habilitada", type: "bool" },
      {
        name: "estado",
        type: "select",
        required: true,
        maxSelect: 1,
        values: ["borrador", "publicado", "finalizado"],
      },
      {
        name: "plantilla_certificado",
        type: "file",
        maxSelect: 1,
        maxSize: 10485760,
        mimeTypes: ["application/pdf", "image/png", "image/jpeg"],
      },
    ],
    indexes: ["CREATE UNIQUE INDEX idx_eventos_slug ON eventos (slug)"],
  },
  {
    ...protectedCollection,
    id: COLLECTION_IDS.inscripciones,
    name: "inscripciones",
    type: "base",
    fields: [
      {
        name: "evento",
        type: "relation",
        required: true,
        maxSelect: 1,
        collectionId: COLLECTION_IDS.eventos,
        cascadeDelete: true,
      },
      { name: "nombres", type: "text", required: true, max: 120 },
      { name: "apellidos", type: "text", required: true, max: 120 },
      { name: "email", type: "email", required: true },
      { name: "documento", type: "text", required: true, max: 32 },
      { name: "documento_normalizado", type: "text", required: true, max: 32 },
      {
        name: "origen",
        type: "select",
        required: true,
        maxSelect: 1,
        values: ["publica", "presencial"],
      },
      { name: "numero_cupo_publico", type: "number", min: 0, max: 100000, onlyInt: true },
      { name: "acreditado", type: "bool" },
      { name: "acreditado_en", type: "date" },
      {
        name: "acreditado_por",
        type: "relation",
        maxSelect: 1,
        collectionId: COLLECTION_IDS.administradores,
        cascadeDelete: false,
      },
    ],
    indexes: [
      "CREATE UNIQUE INDEX idx_inscripciones_documento ON inscripciones (evento, documento_normalizado)",
      "CREATE UNIQUE INDEX idx_inscripciones_cupo ON inscripciones (evento, numero_cupo_publico) WHERE numero_cupo_publico > 0",
      "CREATE INDEX idx_inscripciones_busqueda ON inscripciones (evento, apellidos, nombres)",
    ],
  },
  {
    ...protectedCollection,
    id: COLLECTION_IDS.auditoria,
    name: "auditoria",
    type: "base",
    fields: [
      {
        name: "administrador",
        type: "relation",
        maxSelect: 1,
        collectionId: COLLECTION_IDS.administradores,
        cascadeDelete: false,
      },
      { name: "accion", type: "text", required: true, max: 100 },
      { name: "entidad", type: "text", required: true, max: 80 },
      { name: "entidad_id", type: "text", required: true, max: 40 },
      { name: "datos", type: "json", maxSize: 10000 },
    ],
    indexes: ["CREATE INDEX idx_auditoria_entidad ON auditoria (entidad, entidad_id)"],
  },
  {
    ...protectedCollection,
    id: COLLECTION_IDS.certificados,
    name: "certificados",
    type: "base",
    fields: [
      {
        name: "evento",
        type: "relation",
        required: true,
        maxSelect: 1,
        collectionId: COLLECTION_IDS.eventos,
        cascadeDelete: true,
      },
      {
        name: "inscripcion",
        type: "relation",
        required: true,
        maxSelect: 1,
        collectionId: COLLECTION_IDS.inscripciones,
        cascadeDelete: true,
      },
      {
        name: "archivo",
        type: "file",
        required: true,
        maxSelect: 1,
        maxSize: 10485760,
        mimeTypes: ["application/pdf"],
      },
      { name: "generado_en", type: "date", required: true },
    ],
    indexes: [
      "CREATE UNIQUE INDEX idx_certificados_inscripcion ON certificados (inscripcion)",
    ],
  },
  {
    ...protectedCollection,
    id: COLLECTION_IDS.envios,
    name: "envios_certificados",
    type: "base",
    fields: [
      {
        name: "evento",
        type: "relation",
        required: true,
        maxSelect: 1,
        collectionId: COLLECTION_IDS.eventos,
        cascadeDelete: true,
      },
      {
        name: "inscripcion",
        type: "relation",
        required: true,
        maxSelect: 1,
        collectionId: COLLECTION_IDS.inscripciones,
        cascadeDelete: true,
      },
      {
        name: "certificado",
        type: "relation",
        required: true,
        maxSelect: 1,
        collectionId: COLLECTION_IDS.certificados,
        cascadeDelete: true,
      },
      {
        name: "estado",
        type: "select",
        required: true,
        maxSelect: 1,
        values: ["pendiente", "enviado", "fallido"],
      },
      { name: "intentos", type: "number", min: 0, max: 100, onlyInt: true },
      { name: "ultimo_intento", type: "date" },
      { name: "enviado_en", type: "date" },
      { name: "error", type: "text", max: 1000 },
      { name: "historial", type: "json", maxSize: 20000 },
    ],
    indexes: [
      "CREATE INDEX idx_envios_estado ON envios_certificados (estado, created)",
      "CREATE UNIQUE INDEX idx_envios_certificado ON envios_certificados (certificado)",
    ],
  },
].map((collection) => ({
  ...collection,
  fields: [
    ...collection.fields,
    { name: "created", type: "autodate", onCreate: true, onUpdate: false },
    { name: "updated", type: "autodate", onCreate: true, onUpdate: true },
  ],
})) as unknown as CollectionModel[];
